name: CI
on:
  - push
  - pull_request
jobs:
  x86_64-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        project: ['glfw']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        run: |
          brew install xz
          sudo sh -c 'wget -c https://ziglang.org/builds/zig-macos-x86_64-0.9.0-dev.1785+4cdf5b666.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
      - name: x86_64-macos -> aarch64-macos
        run: cd ${{ matrix.project }} && zig build test -Dtarget=aarch64-macos
        env:
          AGREE: true
